export const tokens = {
  colors: {
    accentStrong: '#6115CD',
    accentStrongMuted: '#C1B5FF',
    background: '#F5F8FD',
    border: '#E6EDF5',
    error: '#111416',
    errorBorder: '#E6EDF5',
    errorSoft: '#FFFFFF',
    likeActive: '#FF2B75',
    likeActiveText: '#FFEAF1',
    lockedOverlay: 'rgba(0,0,0,0.5)',
    lockedSkeleton: 'rgba(238,239,241,0.8)',
    lockedStart: '#6115CD',
    lockedTextSoft: 'rgba(255,255,255,0.92)',
    shadow: '#0F172A',
    surface: '#FFFFFF',
    surfaceMuted: '#EFF2F7',
    text: '#111416',
    textMuted: '#57626F',
    textStrong: '#111416',
    white: '#FFFFFF',
  },
  radii: {
    button: 14,
    md: 10,
    lg: 12,
    pill: 999,
    round: 999,
    xl: 12,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
  },
  fonts: {
    manrope: 'Manrope',
  },
  typography: {
    body: {
      fontSize: 15,
      fontWeight: '500' as const,
      lineHeight: 20,
    },
    bodySmall: {
      fontSize: 13,
      fontWeight: '700' as const,
      lineHeight: 18,
    },
    caption: {
      fontSize: 13,
      fontWeight: '700' as const,
      lineHeight: 18,
    },
    display: {
      fontSize: 18,
      fontWeight: '700' as const,
      letterSpacing: 0,
      lineHeight: 26,
    },
    title: {
      fontSize: 18,
      fontWeight: '700' as const,
      lineHeight: 26,
    },
  },
} as const;
